title = Preferences

switch.darkMode = Dark Mode
switch.darkMode.tooltip = Makes the application's look and feel darker.

switch.fastTarget = Fast Image Target
switch.fastTarget.tooltip = On some particular image formats (only GIF for now), \
  render thumbnails at a compatible image target to boost image rendering.

switch.sortReversed = Reversed Sorting
switch.sortReversed.tooltip = Reverses the sorting order for the file list.

label.cellSize = Thumbnail Size:
label.cellPadding = Thumbnail Padding:
label.threads = Thread Count:
label.cacheBuffer = Icon Cache Buffer:
label.cacheSizeLimit = Icon Cache Size Limit (MB):
label.searchOption = Search Method:
label.sortOption = Sort Method:

label.cellSize.tooltip = The size of the thumbnails shown in the file viewer.
label.cellPadding.tooltip = The internal space padding of the thumbnails shown in the file viewer.
label.threads.tooltip = The number of threads used for background tasks.
label.cacheBuffer.tooltip = The number of additional icons loaded in memory to prevent reloading recently loaded icons.
label.cacheSizeLimit.tooltip = The number of megabytes to keep in the cache.
label.searchOption.tooltip = The method in how the search results will be presented.
label.sortOption.tooltip = How the file list is sorted based on file attributes.

searchOption.scored = Search results are shown based on total search keywords hit, sorted on how many keywords were hit.
searchOption.lenient = Search results are shown based on search keywords, filtering items included by keyword \
  regardless of other keywords.
searchOption.strict = Search results are shown based on search keywords, filtering items included by keywords.

sortOption.name = Sort files by file name.
sortOption.last_modified = Sort files by its last modified date.
sortOption.size = Sort files by file size.
sortOption.tags = Sort files by tags assigned to files.

button.apply = Apply
button.save = OK
button.cancel = Cancel

button.apply.tooltip = Apply the settings without closing this dialog.
button.save.tooltip = Apply the settings and close this dialog.
button.cancel.tooltip = Closes the dialog without applying any settings.

border.switches = Switches