title = Preferences

switch.darkMode = Dark Mode
switch.darkMode.tooltip = Makes the application's look and feel darker.

switch.fastTarget = Fast Image Target
switch.fastTarget.tooltip = On some particular image formats (only GIF for now), \
  render thumbnails at a compatible image target to boost image rendering.

label.cellSize = Thumbnail Size:
label.cellPadding = Thumbnail Padding:
label.threads = Thread Count:
label.cacheBuffer = Icon Cache Buffer:
label.cacheSizeLimit = Icon Cache Size Limit (MB):

label.cellSize.tooltip = The size of the thumbnails shown in the file viewer.
label.cellPadding.tooltip = The internal space padding of the thumbnails shown in the file viewer.
label.threads.tooltip = The number of threads used for background tasks.
label.cacheBuffer.tooltip = The number of additional icons loaded in memory to prevent reloading recently loaded icons.
label.cacheSizeLimit.tooltip = The number of megabytes to keep in the cache.

button.apply = Apply
button.save = OK
button.cancel = Cancel

button.apply.tooltip = Apply the settings without closing this dialog.
button.save.tooltip = Apply the settings and close this dialog.
button.cancel.tooltip = Closes the dialog without applying any settings.

border.switches = Switches