title = Tagged

menu.file = File
menu.file.add = Add Location
menu.file.darkMode = Dark Mode

menu.file.debug = Diagnostics

debug = The memory usage used by GIF images is approx. %d bytes\n\
  Approximately %.2f MB is used by GIF images.\n\
  Approximately %.2f MB of device memory is used by GIF images.\n\
  There are %d entries in the icon cache.\n\
  \n\
  The used Java heap is %.2f MB\n\
  The free Java heap is %.2f MB\n\
  The total being used right now is %.2f MB...\n\
  \n\
  MaxLRUEntries = %d\n\
  The design is very human.\n\
  \n\
  \n\
  Press OK to close the debugger.\ 
debug.title = Diagnostics