title = Tagged

menu.file = File

menu.app = Application
menu.app.add = Locations
menu.app.saveIndex = Save Tags to Disk
menu.app.options = Preferences

menu.app.debug = Diagnostics

status.finding = Found %s
status.finding.done = DONE! Found %d files!!
status.indexWritten = Tags wrote to disk
status.indexRead = Tags read from disk

error.desktop.notSupported = File cannot be opened since the platform cannot support it.
error.desktop.exception = File cannot be opened from an error.
error.loading.iconError = Error from loading icon
error.indexing.fileIndexError = Directory cannot be indexed.
error.indexing.hashIndexError = Files are unable to be hashed.
error.indexing.locationWrite = Recent location data cannot be stored.
error.indexing.indexWrite = Tags for files cannot be stored.
error.loading.locationRead = Recent location data cannot be loaded.
error.loading.indexRead = Tags for files cannot be loaded.
error.preferences.store = Preferences cannot be stored.

dialog.tagEditor = Edit the tags for %s\n; Spaces will be interpreted as a separator for tags.
dialog.removeTag = Remove tags for %s?

menu.context.open = Open
menu.context.showLocation = Show File Location
menu.context.tags = Tags
menu.context.removeTags = Remove Tags

debug = The memory usage used by GIF images is approx. %d bytes\n\
  Approximately %.2f MB is used by GIF images.\n\
  Approximately %.2f MB of device memory is used by GIF images.\n\
  There are %d entries in the icon cache.\n\
  \n\
  The used Java heap is %.2f MB\n\
  The free Java heap is %.2f MB\n\
  The total being used right now is %.2f MB...\n\
  How can I reduce memory usage?\n\
  \n\
  The repaint timer is running? %s\n\
  The repaint timer's delay is %d (%.2f sec) (%.2f /sec)\n\
  \n\
  Shown thumbnail size: %d\n\
  \n\
  MaxLRUEntries = %d\n\
  The design is very human.\n\
  \n\
  \n\
  Press OK to close the diagnostics window.\ 
debug.title = Diagnostics